### ISSUE TITLE
Solar System doesn't create any cards

### ISSUE THREAD

**Issue by issantos** [blinry/wikidata-cardgame#12]
The number Q544 creates a card game consisting of 0 cards

**Comment by blinry** [comment]
Thanks for getting in touch! It's a bit counter-intuitive how the generation works – the generator will try to find items which have the "instance-of" property of a subclass of the supplied topic. Most of the time, a trick that works well is to look up an object you want included, and then click on the instance-of and subclass properties until you arrive at a category you like. For example, here's "planet of the Solar System": https://cardgame.morr.cc/?Q17362350

We could probably extend the documentation to describe that. Thanks again! :)
