### ISSUE TITLE
Thousands separator and rounding decimals

### ISSUE THREAD

**Issue by zx8754** [blinry/wikidata-cardgame#13]
Would be nice to have the separator and decimal rounding.

```
Population: 93863     -> 93,863
Area:       55.604617 -> 55.60
```

![image](https://user-images.githubusercontent.com/5212915/53881895-bf9c7d80-400c-11e9-855d-ba7b00f751df.png)

**Comment by blinry** [comment]
Thanks for suggesting this! I like to use thin spaces as thousands separators, so now it looks like this:

![screenshot-2019-03-08_17 03 41](https://user-images.githubusercontent.com/81277/54039822-2d3eda00-41c4-11e9-9421-df515286a862.png)
