### ISSUE TITLE
Card game for "dish" also returns 3 danish men

### ISSUE THREAD

**Issue by micgro42** [blinry/wikidata-cardgame#19]
There are weird results showing when trying to create a card game for dish ([Q746549](https://www.wikidata.org/wiki/Q746549)):

https://cardgame.morr.cc/?Q746549&lang=en

Aside from some strange art objects that are (wrongly?) classified as dish, there are also three danish men that say that they are instance of human, but they also show up here:

- https://www.wikidata.org/wiki/Q48926395
- https://www.wikidata.org/wiki/Q48926561
- https://www.wikidata.org/wiki/Q49515667

Not sure what is going on there 🤨

**Comment by EdJoPaTo** [comment]
These people had the occupation [kammerjunker](https://www.wikidata.org/wiki/Q123353) which is a biscuit. The job was meant which is [Valet de chambre](https://www.wikidata.org/wiki/Q1723189). I fixed that for these people. So it will be shown in the card games.

**Comment by micgro42** [comment]
Thank you for fixing it :D

I think this issue can now be closed as it was just a case of a confused property value and not an issue in the code of this game generator.
