### ISSUE TITLE
Fails to download image of 1887 Imperial Fabergé egg (Q4193436)

### ISSUE THREAD

**Issue by jaller94** [blinry/wikidata-cardgame#25]
### Steps to reproduce
1. Go to https://cardgame.morr.cc/?Q376&lang=en for clocks

### Expected
Here you go, your card game of clocks.

### Actual
The [image](https://commons.wikimedia.org/wiki/File:Third_imperial_Faberg%C3%A9_egg.svg) of the following item fails to load:
https://www.wikidata.org/wiki/Q4193436

`An error occurred while generating the cards: Error loading https://commons.wikimedia.org/wiki/Special:FilePath/Third%20imperial%20Faberg%C3%A9%20egg.svg?width=1280`

**Comment by blinry** [comment]
That seems to be a problem with Wikimedia Commons, I opened [a ticket on Phabricator](https://phabricator.wikimedia.org/T237539). To work around this issue for now, I lowered the image width to 1000px, which seems to work.

Thanks for reporting this – the clock cards are very pretty!
