### ISSUE TITLE
Provide more complete fallback mechanism for item labels

### ISSUE THREAD

**Issue by blinry** [blinry/wikidata-cardgame#4]
Sometimes, the label service can't get an item label, and thus, we display a Q-number. We should try to get labels in as many languages as possible, and filter out the cards for which we don't have one.

**Comment by EdJoPaTo** [comment]
I think having Q-Numbers aren't that bad as the user then can add the Wikidata labels accordingly. 
Setting your own language might be helpful.

**Comment by bleeptrack** [comment]
I also think showing the Q-Numbers would encourage people to add information :)

**Comment by blinry** [comment]
Agreed! :) I still would prefer a french label to non at all. So we could try putting a long list of language codes in the query?

**Comment by EdJoPaTo** [comment]
A cleaner solution would be to just use the users language(s). (I don't speak French and prefer a Q-Number to something I can't read anyway)

Also it could be fun to just create a [Plattdüütsch](https://nds.wikipedia.org/) set of cards. Or whatever language Wikidata is providing.

One approach could be to just use the browsers language. Or use something like a dropdown? Adding language to the query could be helpful too but would break the current "only q number" logic.

**Comment by bleeptrack** [comment]
> One approach could be to just use the browsers language. Or use something like a dropdown? Adding language to the query could be helpful too but would break the current "only q number" logic.
Yes, we also thought about using the browser language with fallback to english?
Does it break the only-Q-Number logic? I'd say if someone selects Plattdüütsch and there are only few labels, then that might encourage the user to add the missing labels?

**Comment by EdJoPaTo** [comment]
> Does it break the only-Q-Number logic?

Currently its assumed the url search part only contains the Q-Number.
6f61153c4ed37b02c10d0c591d93afa1da147779 improved that behaviour by ignoring everything that is not a number following a Q. 

https://github.com/blinry/wikidata-cardgame/blob/7fd904cb07a358fb25d6340dadd7b45ddf6cfdb6/cardgame.js#L313-L314

Looking at the current behaviour maybe just adding something like this could work:
`…/?Q6999&lang=de,en,fr`
```js
var match = window.location.search.match(/lang=([\w,]+)/g); 
var lang = (match && match[1]) || browserLanguage || "en"; 
```

**Comment by bleeptrack** [comment]
Ah, I see!
I wonder if regex is the best method, especially because there might be more GET-Parameters coming (see #15 ). 
But a quick google search also pointed me to regex matches. So I'm fine with this solution :)
@blinry what do you think? :)

**Comment by EdJoPaTo** [comment]
Maybe something like `window.location.search.slice(1).split('&')` or `.match(/&lang=([^&]+)/)` could ensure matches don't match something they shouldn't match.

An alternative might be key value logic with splits which is also faster compared to RegExp:

https://github.com/bleeptrack/35c3-circuit-generator/blob/f220cc9be43693b3e481ca524568e4681b793641/memories.js#L87-L97

**Comment by blinry** [comment]
ES6 and upwards seem to support *URLSearchParameters*. We will lose [IE, Opera Mini, and Android Browser](https://caniuse.com/#search=urlsearchparams). I think I'm fine with that. :D

We could probably still get the key-less Q-Number with the current approach.

**Comment by EdJoPaTo** [comment]
> ES6 and upwards seem to support _URLSearchParameters_. We will lose [IE, Opera Mini, and Android Browser](https://caniuse.com/#search=urlsearchparams). I think I'm fine with that. :D

API: https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

As thats implemented by the browsers I guess there will be some implementation that is bothered by the missing `=` in the Q-Number entry as it is non standard.

> and Android Browser

I think all important Android Browsers are supported?

**Comment by EdJoPaTo** [comment]
Something that might be helpful: [native label](https://www.wikidata.org/wiki/Property:P1705)

**Comment by blinry** [comment]
As we all seem to like the approach where we only display strings to the user if they are available in the selected language, I'm closing this for now after fixing #16.
